--[[-- INFO -------------------------------------------------------------------
	File				: avo_template
	Description	: Template for avo modules
	Credits			: aVo
	Revision		: 0.3
	Change Date	: 08.03.2014
--]] --------------------------------------------------------------------------

--[[-- TODO -------------------------------------------------------------------
	1. 
--]]---------------------------------------------------------------------------

--/----------------------------------------------------------------------------
--/ Variables & Constants
--/----------------------------------------------------------------------------
local SELF_NAME = script_name()
local is_initialized = false
--/----------------------------------------------------------------------------
--/ Initialization
--/----------------------------------------------------------------------------
function _init(CFG_FILE, module_name)
	if is_initialized then return true end -- already initialized

	local ini = ini_file(CFG_FILE)
	
	local is_enabled = avo.read_ini(ini, "module", "enabled", "bool", false)
	if not is_enabled then
		wlog("-- %s module is disabled", module_name)
		return false
	end
	
	-- do all initializations here
	
	--
	
	is_initialized = true -- mark as initialized
	ini = nil
	wlog("-- %s module is enabled", module_name)
	return true -- initialization successful
end